### ISSUE TITLE
getting the error cannot synchronised guest cart 

### ISSUE THREAD

**Issue by anilahy** [DivanteLtd/magento2-external-checkout#6] opened 2018-03-28 11:12 UTC
there is an issue when adding product as a guest user and completing the checkout form magento2
it works for the first time but repeating the same thing with gust user. it gives error:
 Cannot synchronize guest cart

**Comment by pkarw** [comment] 2018-03-28 11:15
https://github.com/DivanteLtd/magento2-external-checkout/pull/5/filesPlease check this fix
--

**Comment by anilahy** [comment] 2018-03-28 12:11
@pkarw 
I get the latest pull of the module but still not resolved.

**Comment by pkarw** [comment] 2018-03-29 17:46
Duplicate of #4 Closing this one

**Closed as completed by pkarw** 2018-03-29 17:46 UTC
